[versions]
aspectj = "1.9.21"
spring-expression = "6.1.14"
slf4j = "2.0.16"
junit = "5.11.4"
assertj = "3.26.3"

[libraries]
aspectj-rt = { module = "org.aspectj:aspectjrt", version.ref = "aspectj" }
aspectj-weaver = { module = "org.aspectj:aspectjweaver", version.ref = "aspectj" }
spring-context = { module = "org.springframework:spring-context", version.ref = "spring-expression" }
spring-expression = { module = "org.springframework:spring-expression", version.ref = "spring-expression" }
spring-test = { module = "org.springframework:spring-test", version.ref = "spring-expression" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj" }
